### ISSUE TITLE
Expose the raw Popolo Hash

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician-popolo#20]
Sometimes you just want to reach into the popolo hash for something that isn't (yet) exposed though the gem's API.

**Comment by chrismytton** [comment]
This would be useful to tidy up [this bit of code in viewer-sinatra](https://github.com/everypolitician/viewer-sinatra/blob/02b8fb4e4f1a5a696fd50d68075af1e90c67d7db/app.rb#L126-L127) so we don't have to parse the popolo twice.

**Comment by henare** [comment]
You [can already](https://github.com/everypolitician/everypolitician-popolo/blob/master/lib/everypolitician/popolo.rb#L24):

``` ruby
popolo = EveryPolitician::Popolo.read("some_popolo.json")
tomato = popolo.popolo[:meta][:sauces]
```

We're [doing it](https://github.com/OPORA/publicwhip/blob/develop/lib/data_loader/ukraine/vote_events.rb#L25) for `vote_events` on rada4you.org.

**Comment by chrismytton** [comment]
Oh yeah, how did I miss this?! Thanks @henare!
