### ISSUE TITLE
Equality should check class as well as id

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician-popolo#24]
The [current equality check](https://github.com/everypolitician/everypolitician-popolo/blob/be22bd81c598ae0602c5ddf8e9fdb8a783745877/lib/everypolitician/popolo/person.rb#L25-L28) only looks to see if two items have the same `id`. It should really also check that items are of the same class as well.

**Comment by tmtmtmtm** [comment]
@ondenman This looks like one you could usefully do. Add a test to show that a Person with ID 1 currently incorrectly == an Organization with ID 1, and then fix that.

**Comment by ondenman** [comment]
@tmtmtmtm This method has since been placed in the Entity class.
