### ISSUE TITLE
Method for accessing terms in Popolo

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician-popolo#35]
# Problem

As part of https://github.com/everypolitician/everypolitician/issues/467 we need to be able to access the most recent term in the Popolo file.
# Proposed Solution

Add a `terms` method (aliased to `legislative_periods`) which returns an array of all terms, most recent first. There should also be a `current_term` method which returns the most recent term available (though it might not actually be the current term).
# Acceptance Criteria

~~I should be able to access all of the people and parties that are in the latest term for a given legislature using this gem.~~ (moving this to a separate issue, see comments below)

I should be able to access _just_ the terms, without having to filter the events. I should also be able to get the most recent term that is available in the popolo.
# Not Required
# Prerequisites
-  [x] Add connections between collections  https://github.com/everypolitician/everypolitician-popolo/issues/39
# Related Issues
- Add counts of Email|Facebook|Twitter to stats.json  https://github.com/everypolitician/everypolitician/issues/467
# Due Date
# Design?
# Text?
# Bloggable?

**Comment by tmtmtmtm** [comment]
The acceptance criteria for this seem to connected to something slightly different. Being able to access the list of terms, or specifically get the current term, seems considerably simpler than being able to then get a list of the people and parties from that…

**Comment by chrismytton** [comment]
@tmtmtmtm Yes good point, I seem to have conflated two separate issues here:
1. Method to access just terms, instead of all events
2. Method to get at the people/parties etc that relate to a term

This ticket was intended to be about 1., I'll edit the acceptance criteria to reflect that. I'll open a separate ticket about 2.

As a nice bonus splitting this ticket in two means that https://github.com/everypolitician/everypolitician-popolo/pull/38 should satisfy the requirements for 1.
