### ISSUE TITLE
Use real popolo files in the tests

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/everypolitician-popolo#42]
# Problem

Lots of tests construct elaborate popolo objects using hashes, but nothing is done in a terribly consistent or straightforward way.
# Proposed Solution

We should pull in an actual popolo file (or possibly multiple files) and run the tests against real world data. @tmtmtmtm suggests that somewhere with lots of data, like Turkey, would be a good option as it would also point towards any possible performance issues if there tests are slow.
# Acceptance Criteria

Writing a new test should not require me to construct a popolo hash by hand, other than the odd time where we're testing an edge case that isn't represented in the popolo (though arguably that should probably just be another popolo test fixture).
# Not Required

We don't need to dynamically pull the files from EveryPolitician or record the request with VCR or anything. For now just manually copying the file over occasionally should be Good Enough.
# Prerequisites

None.
# Related Issues
- https://github.com/everypolitician/everypolitician-popolo/pull/41 was the pull request review that prompted @tmtmtmtm to suggest using a real popolo file.

**Comment by tmtmtmtm** [comment]
👍  from me on this. I got bitten last weekend again by something passing tests here, but blowing up against real-world data.

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/everypolitician-popolo/pull/56
